
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const REQUEST_SEARCH_SUCCESS = 'REQUEST_SEARCH_SUCCESS';
export const REQUEST_SEARCH_FAILURE = 'REQUEST_SEARCH_FAILURE';

export const REQUEST_FETCH_ACCESS_TOKEN = 'REQUEST_FETCH_ACCESS_TOKEN';
export const REQUEST_FETCH_ACCESS_TOKEN_SUCCESS = 'REQUEST_FETCH_ACCESS_TOKEN_SUCCESS';
export const REQUEST_FETCH_ACCESS_TOKEN_FAILURE = 'REQUEST_FETCH_ACCESS_TOKEN_FAILURE';
